### ISSUE TITLE
Import Error: No module named 'static_precompiler'

### ISSUE THREAD

**Issue by praneethkumarpidugu** [aristotle-mdr/aristotle-metadata-registry#134]
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/praneeth/wru-pam/venv/lib/python3.4/site-packages/django/core/management/**init**.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/praneeth/wru-pam/venv/lib/python3.4/site-packages/django/core/management/**init**.py", line 354, in execute
    django.setup()
  File "/home/praneeth/wru-pam/venv/lib/python3.4/site-packages/django/**init**.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/praneeth/wru-pam/venv/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/praneeth/wru-pam/venv/lib/python3.4/site-packages/django/apps/config.py", line 87, in create
    module = import_module(entry)
  File "/home/praneeth/wru-pam/venv/lib/python3.4/importlib/**init**.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2201, in _find_and_load_unlocked
ImportError: No module named 'static_precompiler'

**Comment by LegoStormtroopr** [comment]
How did you install Aristotle?

`django-static-precompiler` is listed in [setup.py](https://github.com/LegoStormtroopr/aristotle-metadata-registry/blob/master/setup.py#L56) which has most of the requirements.

**Comment by LegoStormtroopr** [comment]
Try installing like so:

    pip install -e git+git@git.myproject.org:MyProject#egg=MyProject

As always, [make sure you do so in a virtualenv](https://virtualenv.pypa.io/en/latest/)
