### ISSUE TITLE
Intermittent failure of test suite (catch all)

### ISSUE THREAD

**Issue by LegoStormtroopr** [aristotle-mdr/aristotle-metadata-registry#162]
Occasionally a build will fail with an item being public when it shouldn't be, this is usually corrected by rerunning the test. It seems like its a caching issue, but needs to be investigated.

From the [test logs on Travis-CI](https://travis-ci.org/aristotle-mdr/aristotle-metadata-registry/jobs/59328475)

```
These items failed the check for ConceptQuerySet.visible():
user= viewer1 default 0
item= Concept 1 default 0
      [<Status: Concept 1 default 0 is Standard for permission_check 0 Default RA>]
```

```
======================================================================
FAIL: test_is_visible (aristotle_mdr.tests.test_permissions.CustomConceptQuerySetTest_RegistrationOwned_Slow)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/aristotle-mdr/aristotle-metadata-registry/aristotle_mdr/tests/test_permissions.py", line 335, in test_is_visible
    name="ConceptQuerySet.visible()"
  File "/home/travis/build/aristotle-mdr/aristotle-metadata-registry/aristotle_mdr/tests/test_permissions.py", line 322, in abstract_queryset_check
    self.assertEqual(len(invalid_items),0)
AssertionError: 1 != 0
----------------------------------------------------------------------
```

**Comment by LegoStormtroopr** [comment]
Another example here: https://travis-ci.org/aristotle-mdr/aristotle-metadata-registry/jobs/64649068

**Comment by LegoStormtroopr** [comment]
Again: https://travis-ci.org/aristotle-mdr/aristotle-metadata-registry/jobs/65097996

It seems like the original error was removed when the timestamp changes for search were fixed, but the admin errors still persist.

**Comment by LegoStormtroopr** [comment]
https://travis-ci.org/aristotle-mdr/aristotle-metadata-registry/jobs/65818421

    ======================================================================
    FAIL: test_editor_can_make_object (aristotle_mdr.tests.test_wizards.PropertyWizardPage)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/travis/build/aristotle-mdr/aristotle-metadata-registry/aristotle_mdr/tests/test_wizards.py", line 140, in test_editor_can_make_object
        self.assertEqual(response.status_code, 302)
    AssertionError: 200 != 302

**Comment by LegoStormtroopr** [comment]
Hmmm... looks like this is related to using `pk` of a workgroup attached to an item. Switching to us `id` seems to be correcting this. Looks like a test/transaction issue

**Comment by LegoStormtroopr** [comment]
New ones:
```
======================================================================
ERROR: test_registration_authority_inline_not_in_editor_admin_page (aristotle_mdr.tests.test_extension_api.QuestionnaireAdmin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/aristotle-mdr/aristotle-metadata-registry/aristotle_mdr/tests/test_admin_pages.py", line 155, in test_registration_authority_inline_not_in_editor_admin_page
    self.assertEqual(self.item1.current_statuses()[0].state,models.STATES.incomplete)
IndexError: list index out of range
======================================================================
FAIL: test_registrar_can_change_status (aristotle_mdr.tests.test_html_pages.ConceptualDomainViewPage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/aristotle-mdr/aristotle-metadata-registry/aristotle_mdr/tests/test_html_pages.py", line 341, in test_registrar_can_change_status
    self.assertTrue(self.item1.is_public())
AssertionError: False is not true
```

**Comment by LegoStormtroopr** [comment]
Looks like all the bugs around this are ironed out in pull #210
