### ISSUE TITLE
Easy Install Errors

### ISSUE THREAD

**Issue by rknowles9** [aristotle-mdr/aristotle-metadata-registry#801]
(I apologize for making this an issue, but I can't seem to find a place or group to just ask about Aristotle.) 

I'm following instructions from [http://aristotle-metadata-registry.readthedocs.io/en/stable/installing/easy_install.html](url) to just install MDR. I find I hit errors and have to edit files and install different versions of requirements. I fear I'm just doing something wrong, and that my changes may just be leading me down a bad path, where I fix one thing and break another. To explain, here's a fresh attempt from today:
```
[myhost aristotle]$ python --version
Python 2.7.13
[myhost aristotle]$ virtualenv venv2May
...
[myhost aristotle]$ cd venv2May/
[myhost venv2May]$ source bin/activate.csh 
[venv2May] [myhost venv2May]$ pip install aristotle-metadata-registry
... [Lots of good output, but ...]
channels 2.1.1 has requirement asgiref~=2.3, but you'll have asgiref 1.1.2 which is incompatible.
channels 2.1.1 has requirement Django>=1.11, but you'll have django 1.10.8 which is incompatible.
...
[venv2May] [myhost venv2May]$
```
I found channels 1.1.8, instead of 2.1.1,  would get by the problems above
```
[venv2May] [myhost venv2May]$ pip install channels==1.1.8
...
[venv2May] [myhost venv2May]$ pip install aristotle-metadata-registry
... [Now,no errors]
[venv2May] [myhost venv2May]$ python -m aristotle_mdr.install.easy
Enter the system name for your registry (lowercase letters and underscores ONLY): mdr_reg
Attempting to retrieve example registry
svn: E170000: URL 'https://github.com/aristotle-mdr/aristotle-metadata-registry/trunk/aristotle_mdr/install/example_mdr' doesn't exist
Traceback (most recent call last):
  File "/ll/3rdptysw/x86_64-Linux-2.6.32/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/ll/3rdptysw/x86_64-Linux-2.6.32/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/mixite/1/rknowles/aristotle/venv2May/lib/python2.7/site-packages/aristotle_mdr/install/easy.py", line 216, in <module>
    sys.exit(main())
  File "/home/mixite/1/rknowles/aristotle/venv2May/lib/python2.7/site-packages/aristotle_mdr/install/easy.py", line 212, in main
    return setup_mdr(**kwargs)
  File "/home/mixite/1/rknowles/aristotle/venv2May/lib/python2.7/site-packages/aristotle_mdr/install/easy.py", line 68, in setup_mdr
    rename_example_mdr(name)
  File "/home/mixite/1/rknowles/aristotle/venv2May/lib/python2.7/site-packages/aristotle_mdr/install/easy.py", line 124, in rename_example_mdr
    os.rename('example_mdr', name)
OSError: [Errno 2] No such file or directory
[venv2May] [myhost venv2May]$
```
Now it can't download example_mdr. To fix this problem I edited lib/python2.7/site-packages/aristotle_mdr/install/easy.py,
download_example_mdr(), changing:
```
    arg = "https://github.com/aristotle-mdr/aristotle-metadata-registry/trunk/aristotle_mdr/install/example_mdr/"
```
to
```
    arg = "https://github.com/aristotle-mdr/aristotle-metadata-registry/branches/master/aristotle_mdr/install/example_mdr/" 
```
Then
```
[venv2May] [myhost venv2May]$ python -m aristotle_mdr.install.easy
Enter the system name for your registry (lowercase letters and underscores ONLY): mdr_reg
Attempting to retrieve example registry
A    example_mdr
A    example_mdr/README.rst
A    example_mdr/example_mdr
A    example_mdr/example_mdr/__init__.py
A    example_mdr/example_mdr/settings.py
A    example_mdr/example_mdr/urls.py
A    example_mdr/example_mdr/wsgi.py
A    example_mdr/manage.py
A    example_mdr/requirements.txt
Exported revision 3463.
Do you wish to install any additional Aristotle modules? (y/n): y
Select extensions to install (y/n)
  Aristotle Glossary Extension: y
  Aristotle Dataset Extensions: y
  Aristotle DDI Downloaders: y
  Aristotle MDR API: y
Ready to install requirements? (y/n): y
Requirement already satisfied: aristotle-metadata-registry>=1.5 in ./lib/python2.7/site-packages (from -r mdr_reg/requirements.txt (line 3)) (1.6.5)
Collecting Whoosh (from -r mdr_reg/requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/ba/19/24d0f1f454a2c1eb689ca28d2f178db81e5024f42d82729a4ff6771155cf/Whoosh-2.7.4-py2.py3-none-any.whl
Obtaining aristotle-dse from git+git://github.com/aristotle-mdr/aristotle-dataset-extensions#egg=aristotle-dse (from -r mdr_reg/requirements.txt (line 6))
  Cloning git://github.com/aristotle-mdr/aristotle-dataset-extensions to ./src/aristotle-dse
fatal: read error: Connection reset by peer
Command "git clone -q git://github.com/aristotle-mdr/aristotle-dataset-extensions /home/mixite/1/rknowles/aristotle/venv2May/src/aristotle-dse" failed with error code 128 in None
Running django command to fetch all required static files
Traceback (most recent call last):
  File "./mdr_reg/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mixite/1/rknowles/aristotle/venv2May/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/mixite/1/rknowles/aristotle/venv2May/lib/python2.7/site-packages/django/core/management/__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "/home/mixite/1/rknowles/aristotle/venv2May/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/home/mixite/1/rknowles/aristotle/venv2May/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/mixite/1/rknowles/aristotle/venv2May/lib/python2.7/site-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/ll/3rdptysw/x86_64-Linux-2.6.32/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/mixite/1/rknowles/aristotle/venv2May/mdr_reg/mdr_reg/settings.py", line 29, in <module>
    from aristotle_glossary.settings import CKEDITOR_CONFIGS
ImportError: No module named aristotle_glossary.settings
Traceback (most recent call last):
  File "./mdr_reg/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mixite/1/rknowles/aristotle/venv2May/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/mixite/1/rknowles/aristotle/venv2May/lib/python2.7/site-packages/django/core/management/__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "/home/mixite/1/rknowles/aristotle/venv2May/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/home/mixite/1/rknowles/aristotle/venv2May/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/mixite/1/rknowles/aristotle/venv2May/lib/python2.7/site-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/ll/3rdptysw/x86_64-Linux-2.6.32/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/mixite/1/rknowles/aristotle/venv2May/mdr_reg/mdr_reg/settings.py", line 29, in <module>
    from aristotle_glossary.settings import CKEDITOR_CONFIGS
ImportError: No module named aristotle_glossary.settings
You can now locally test your installed registry by running the command './manage.py runserver'
[venv2May] [myhost venv2May]$
```
It can't get aristotle-dse. I discovered that if I fix that, then it can't get the next extension, and so on for all four. My fix for this is to restart the install, answer 'y' to additional modules, answer 'y' to the four modules, then pause. Now, I edit mdr_reg//requirements.txt, and change "git+git" to "git+https" for all four modules.
```
[venv2May] [myhost venv2May]$ rm -fr mdr_reg/
[venv2May] [myhost venv2May]$ python -m aristotle_mdr.install.easy
Enter the system name for your registry (lowercase letters and underscores ONLY): mdr_reg
...
Do you wish to install any additional Aristotle modules? (y/n): y
Select extensions to install (y/n)
  Aristotle Glossary Extension: y
  Aristotle Dataset Extensions: y
  Aristotle DDI Downloaders: y
  Aristotle MDR API: y
Ready to install requirements? (y/n): 
```
Now, go edit requirements.txt, then continue:
```
Ready to install requirements? (y/n): y
Requirement already satisfied: aristotle-metadata-registry>=1.5 in ./lib/python2.7/site-packages (from -r mdr_reg/requirements.txt (line 3)) (1.6.5)
Collecting Whoosh (from -r mdr_reg/requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/ba/19/24d0f1f454a2c1eb689ca28d2f178db81e5024f42d82729a4ff6771155cf/Whoosh-2.7.4-py2.py3-none-any.whl
Obtaining aristotle-dse from git+https://github.com/aristotle-mdr/aristotle-dataset-extensions#egg=aristotle-dse (from -r mdr_reg/requirements.txt (line 6))
  Cloning https://github.com/aristotle-mdr/aristotle-dataset-extensions to ./src/aristotle-dse
  Running setup.py (path:/home/mixite/1/rknowles/aristotle/venv2May/src/aristotle-dse/setup.py) egg_info for package aristotle-dse produced metadata for project name django-aristotle-dataset-extensions. Fix your #egg=aristotle-dse fragments.
  ... [The other 3 get cloned okay.]
  ... [Lots more good output.]
```
But then
```
Running django command to fetch all required static files
Traceback (most recent call last):
  File "./mdr_reg/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mixite/1/rknowles/aristotle/venv2May/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/mixite/1/rknowles/aristotle/venv2May/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/mixite/1/rknowles/aristotle/venv2May/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/mixite/1/rknowles/aristotle/venv2May/lib/python2.7/site-packages/django/core/management/base.py", line 342, in execute
    self.check()
  File "/home/mixite/1/rknowles/aristotle/venv2May/lib/python2.7/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/mixite/1/rknowles/aristotle/venv2May/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
    issues.extend(super(Command, self)._run_checks(**kwargs))
  File "/home/mixite/1/rknowles/aristotle/venv2May/lib/python2.7/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/mixite/1/rknowles/aristotle/venv2May/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/mixite/1/rknowles/aristotle/venv2May/lib/python2.7/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/mixite/1/rknowles/aristotle/venv2May/lib/python2.7/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/home/mixite/1/rknowles/aristotle/venv2May/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/mixite/1/rknowles/aristotle/venv2May/lib/python2.7/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/mixite/1/rknowles/aristotle/venv2May/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/mixite/1/rknowles/aristotle/venv2May/lib/python2.7/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/ll/3rdptysw/x86_64-Linux-2.6.32/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/mixite/1/rknowles/aristotle/venv2May/mdr_reg/mdr_reg/urls.py", line 1, in <module>
    from django.conf.urls import patterns, include, url
ImportError: cannot import name patterns

You have requested to collect static files at the destination
location as specified in your settings:

    /home/mixite/1/rknowles/aristotle/venv2May/mdr_reg/static

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: no
CommandError: Collecting static files cancelled.
You can now locally test your installed registry by running the command './manage.py runserver'
[venv2May] [myhost venv2May]$ 
```
Now there's an import error. I won't continue fully here, but as errors cascade I've also changed versions of several things:
```
	pip install djangorestframework==3.7.3
	pip install django==1.8.19
	pip install django-haystack==2.6.1
```
And I've edited to change DOWNLOADERS, HAYSTACK_CONNECTIONS, various URLs. I must be missing something, cause this doesn't feel easy at all. Thanks for any advice or help on this.

**Comment by harrywhite4** [comment]
Hey, 
I have actually just re written the easy installer to address most of these issues. 
Although i notice you are using python 2.7, we are currently supporting 3.5 and above so this is likely causing some problems.

If you want to try the new installer it can be found here:
https://raw.githubusercontent.com/harrywhite4/aristotle-metadata-registry/easyinstall/python/easy-installer/install.py

You can just run it in the directory you want to install in with python3 and it should handle the rest. Let me know if you have any issues with it. It also has some command line options you can view with `install.py --help`

**Comment by rknowles9** [comment]
Thanks! Unfortunately, here's how this starts for me:
```
[myhost aristotle]$ virtualenv -p python3 venv3May
Running virtualenv with interpreter /ll/3rdptysw/x86_64-Linux-2.6.32/bin/python3
Using base prefix '/ll/3rdptysw/x86_64-Linux-2.6.32'
New python executable in /home/mixite/1/rknowles/aristotle/venv3May/bin/python3
Also creating executable in /home/mixite/1/rknowles/aristotle/venv3May/bin/python
Installing setuptools, pip, wheel...done.
[myhost aristotle]$ cd venv3May/
[myhost venv3May]$ source bin/activate.csh 
[venv3May] [myhost venv3May]$ python --version
Python 3.6.3
[venv3May] [myhost venv3May]$ python ../mdr-install.py 
Enter the system name for your registry (lowercase letters and underscores ONLY): mdr_reg
Copying in example metadata registry
requests must be installed to download the example registry
run "pip install requests" to install
Traceback (most recent call last):
  File "../mdr-install.py", line 257, in <module>
    sys.exit(main())
  File "../mdr-install.py", line 254, in main
    return setup_mdr(args)
  File "../mdr-install.py", line 80, in setup_mdr
    download_example_mdr(directory)
  File "../mdr-install.py", line 186, in download_example_mdr
    import requests
ModuleNotFoundError: No module named 'requests'
[venv3May] [myhost venv3May]$ pip install requests
Collecting requests
  Using cached https://files.pythonhosted.org/packages/49/df/50aa1999ab9bde74656c2919d9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests)
  Using cached https://files.pythonhosted.org/packages/27/cc/6dd9a3869f15c2edfab863b992838277279ce92663d334df9ecf5106f5c6/idna-2.6-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests)
  Using cached https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests)
  Using cached https://files.pythonhosted.org/packages/63/cb/6965947c13a94236f6d4b8223e21beb4d576dc72e8130bd7880f600839b8/urllib3-1.22-py2.py3-none-any.whl
Installing collected packages: idna, certifi, chardet, urllib3, requests
Successfully installed certifi-2018.4.16 chardet-3.0.4 idna-2.6 requests-2.18.4 urllib3-1.22
[venv3May] [myhost venv3May]$ python ../mdr-install.py -n mdr_reg
Traceback (most recent call last):
  File "../mdr-install.py", line 257, in <module>
    sys.exit(main())
  File "../mdr-install.py", line 254, in main
    return setup_mdr(args)
  File "../mdr-install.py", line 64, in setup_mdr
    use_existing_files = check_example_exists(directory, name, yn)
  File "../mdr-install.py", line 165, in check_example_exists
    dest = os.path.join(dir, name)
  File "/home/mixite/1/rknowles/aristotle/venv3May/lib/python3.6/posixpath.py", line 92, in join
    genericpath._check_arg_types('join', a, *p)
  File "/home/mixite/1/rknowles/aristotle/venv3May/lib/python3.6/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'list'
[venv3May] [myhost venv3May]$ 
```
Do I have some other 2.7 things hanging around my new virtualenv? The only thing it shows is venv3May/lib/python3.6. Maybe I'm missing other modules?

**Comment by rknowles9** [comment]
Hi @harrywhite4,

I'm trying to push past some errors and now encountering permission problems in my virtual environment.
```
[myhost aristotle]$ virtualenv -p python3 venv3May
Running virtualenv with interpreter /ll/3rdptysw/x86_64-Linux-2.6.32/bin/python3
Using base prefix '/ll/3rdptysw/x86_64-Linux-2.6.32'
New python executable in /home/mixite/1/rknowles/aristotle/venv3May/bin/python3
Also creating executable in /home/mixite/1/rknowles/aristotle/venv3May/bin/python
Installing setuptools, pip, wheel...done.
[myhost aristotle]$ cd venv3May/
[myhost venv3May]$ source bin/activate.csh 
[venv3May] [myhost venv3May]$ pip install requests
Collecting requests
... [All okay]
[venv3May] [myhost venv3May]$ python ../mdr-install.py 
Enter the system name for your registry (lowercase letters and underscores ONLY): mdr_reg
Copying in example metadata registry
Attempting to retrieve example registry
Traceback (most recent call last):
  File "../mdr-install.py", line 257, in <module>
    sys.exit(main())
  File "../mdr-install.py", line 254, in main
    return setup_mdr(args)
  File "../mdr-install.py", line 82, in setup_mdr
    rename_example_mdr(name, directory)
  File "../mdr-install.py", line 146, in rename_example_mdr
    find_and_replace(directory, 'example_mdr', name)
  File "../mdr-install.py", line 227, in find_and_replace
    with open(fpath, "w") as f:
PermissionError: [Errno 13] Permission denied: '/home/mixite/1/rknowles/aristotle/venv3May/lib/python3.6/_bootlocale.py'
[venv3May] [myhost venv3May]$ 
```
I went to venv3May/lib/python3.6 where _bootlocale.py is a link back to my system _bootlocale.py, and I don't have write permission on that. So, I made my own copy with permissions and tried again.
```
[venv3May] [myhost venv3May]$ python ../mdr-install.py 
[Same stuff until ...]
Traceback (most recent call last):
  File "../mdr-install.py", line 257, in <module>
    sys.exit(main())
  File "../mdr-install.py", line 254, in main
    return setup_mdr(args)
  File "../mdr-install.py", line 95, in setup_mdr
    find_and_remove(directory, extensions)
  File "../mdr-install.py", line 240, in find_and_remove
    with open(fpath, "w") as f:
PermissionError: [Errno 13] Permission denied: '/home/mixite/1/rknowles/aristotle/venv3May/lib/python3.6/locale.py'
```
Go make a copy of locale.py.
```
[venv3May] [myhost venv3May]$ python ../mdr-install.py 
[Same stuff until ...]
Traceback (most recent call last):
  File "../mdr-install.py", line 257, in <module>
    sys.exit(main())
  File "../mdr-install.py", line 254, in main
    return setup_mdr(args)
  File "../mdr-install.py", line 95, in setup_mdr
    find_and_remove(directory, extensions)
  File "../mdr-install.py", line 240, in find_and_remove
    with open(fpath, "w") as f:
PermissionError: [Errno 13] Permission denied: '/home/mixite/1/rknowles/aristotle/venv3May/lib/python3.6/hashlib.py'
```
And, once again...
```
[venv3May] [myhost venv3May]$ python ../mdr-install.py 
[Same stuff until ...]
Traceback (most recent call last):
  File "../mdr-install.py", line 257, in <module>
    sys.exit(main())
  File "../mdr-install.py", line 254, in main
    return setup_mdr(args)
  File "../mdr-install.py", line 95, in setup_mdr
    find_and_remove(directory, extensions)
  File "../mdr-install.py", line 240, in find_and_remove
    with open(fpath, "w") as f:
PermissionError: [Errno 13] Permission denied: '/home/mixite/1/rknowles/aristotle/venv3May/lib/python3.6/io.py'
[venv3May] [myhost venv3May]$ 
```
etc.

**Comment by harrywhite4** [comment]
So i should have mentioned you have to install requests, but it looks like you got that. Seems like this -n option isn't working i'l look into that. As for the permissions issues it seems the error is happening on find_and_remove. So it may work when selecting no for any additional modules (you can still install these later)

**Comment by rknowles9** [comment]
@harrywhite4 - I can now get my server to come up. The successful sequence was this:
```
=> virtualenv -p python3.5 venv
...
=> source venv/bin/activate.csh
=> pip install requests
...
=> pip install channels==1.1.8
...
=> python ./install.py
# [Skip additional modules]
...
=> cd <somewhere away from venv>
=> python mdr_reg/manage.py runserver
```
I avoided '-n' and moved to a different place to install aristotle, as your last two comments suggested. It still wouldn't work until I changed 'channels' to 1.1.8.

Now the server is running and I can see several different windows. However 'Help' is empty and there are no data to browse. I guess I need a pointer now to get the help files, to add the additional  modules I skipped, to add users (if I need to), andhow to start adding my own data. 

Thanks for your attention and help on this .

**Comment by rknowles9** [comment]
@harrywhite4 - I can now get my server to come up. The successful sequence was this:
```
=> virtualenv -p python3.5 venv
...
=> source venv/bin/activate.csh
=> pip install requests
...
=> pip install channels==1.1.8
...
=> python ./install.py
# [Skip additional modules]
...
=> cd <somewhere away from venv>
=> python mdr_reg/manage.py runserver
```
I avoided '-n' and moved to a different place to install aristotle, as your last two comments suggested. It still wouldn't work until I changed 'channels' to 1.1.8.

Now the server is running and I can see several different windows. However 'Help' is empty and there are no data to browse. I guess I need a pointer now to get the help files, to add the additional  modules I skipped, to add users (if I need to), andhow to start adding my own data. 

Thanks for your attention and help on this .

**Comment by harrywhite4** [comment]
So channels 1.1.8 is what we are using aswell so thats fine. As for the help you can load it in with `manage.py loadhelp` and you can create an initial user with `manage.py createsuperuser` . The extension you can install by uncommenting them from requirements.txt doing an install from there with `pip install -r requirements.txt` and then uncommenting them from installed apps in settings.py

**Comment by rknowles9** [comment]
Thanks again, @harrywhite4. I now have it up and running! The latest manage.py certainly has more options than it used to, so that's helping. I tried to use the 4 optional pieces but there are some requirement version problems. Looking at the source repos, they're all older than the latest MDR, so I suspect they have to be brought  up to date. I'm going to look at them separately to see if I can get them working, or if any of the 4 already do work. But at the moment, we can go to work actually trying out metadata!

**Comment by rknowles9** [comment]
Thanks again, @harrywhite4. I now have it up and running! The latest manage.py certainly has more options than it used to, so that's helping. I tried to use the 4 optional pieces but there are some requirement version problems. Looking at the source repos, they're all older than the latest MDR, so I suspect they have to be brought  up to date. I'm going to look at them separately to see if I can get them working, or if any of the 4 already do work. But at the moment, we can go to work actually trying out metadata!
