### ISSUE TITLE
ModuleNotFoundError: No module named 'whoosh'

### ISSUE THREAD

**Issue by derrix060** [aristotle-mdr/aristotle-metadata-registry#807]
I've installed the `aristotle_metadata_registry` using `pip install -r requirements.txt` and this was the log:

```bash
(aristotleEnv)  ✘ mario@mario-N43SM  ~/Projects/aristotle-metadata-registry/python/aristotle-metadata-registry   develop ●  pip install -r requirements.txt
Looking in indexes: https://pypi.python.org/simple/
Obtaining file:///home/mario/Projects/aristotle-metadata-registry/python/aristotle-metadata-registry (from -r requirements.txt (line 6))
Collecting django-model-utils==3.0.0 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/78/09/b96cb191b0e793c7f6284e9630bda3df8830b44dca18a65d5d0fdf094259/django-model-utils-3.0.0.tar.gz
Collecting django-haystack-channels==0.0.1b (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/37/2a/2fa52757c5e6e180b96466aa03976b1511267ecad31f37ed2ed26e507094/django-haystack-channels-0.0.1b.tar.gz
Collecting Django<2.0,>=1.11.1 (from aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/25/4d/c8228419346a0e84aec202a43e181afc6572b861d38f8a0306dbce6abef0/Django-1.11.13-py2.py3-none-any.whl (6.9MB)
    100% |████████████████████████████████| 7.0MB 3.0MB/s 
Collecting six (from aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting pytz (from aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/dc/83/15f7833b70d3e067ca91467ca245bae0f6fe56ddc7451aa0dc5606b120f2/pytz-2018.4-py2.py3-none-any.whl (510kB)
    100% |████████████████████████████████| 512kB 7.5MB/s 
Collecting pyyaml (from aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/4a/85/db5a2df477072b2902b0eb892feb37d88ac635d36245a72a6a69b23b383a/PyYAML-3.12.tar.gz (253kB)
    100% |████████████████████████████████| 256kB 27.0MB/s 
Collecting lesscpy (from aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/10/d0/fdd9874972e07ae8727a3d26b433891d8605b96999ea99bbf506e756a7b1/lesscpy-0.13.0-py2.py3-none-any.whl (48kB)
    100% |████████████████████████████████| 51kB 4.8MB/s 
Collecting django-notifications-hq>=1.0 (from aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/49/fd/7756dd010768ef4159949fe145f507ddeb3dcafc941a8df843e3b9e4d071/django_notifications_hq-1.3-py2.py3-none-any.whl
Collecting django-braces (from aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/84/3c/fa2cca1411b456a84714efea8a2c805924eba6147e6b68e326caca9c7383/django_braces-1.13.0-py2.py3-none-any.whl
Collecting docutils (from aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/36/fa/08e9e6e0e3cbd1d362c3bbee8d01d0aedb2155c4ac112b19ef3cae8eed8d/docutils-0.14-py3-none-any.whl (543kB)
    100% |████████████████████████████████| 552kB 3.6MB/s 
Collecting django-haystack<2.8.0,>=2.7.dev1 (from aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/db/27/fcfe182d2b40fac6976cf51c954023e08a3889d35ffd889223cf05175440/django-haystack-2.7.0.tar.gz (1.6MB)
    100% |████████████████████████████████| 1.6MB 4.3MB/s 
Collecting django-ckeditor>=5.3.0 (from aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/41/69/da0dbe563ed0bda0551435dee922717569dec32f111bdb75f66aec7ea7d7/django-ckeditor-5.4.0.tar.gz (1.6MB)
    100% |████████████████████████████████| 1.6MB 3.4MB/s 
Collecting pillow (from aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/5f/4b/8b54ab9d37b93998c81b364557dff9f61972c0f650efa0ceaf470b392740/Pillow-5.1.0-cp36-cp36m-manylinux1_x86_64.whl (2.0MB)
    100% |████████████████████████████████| 2.0MB 4.5MB/s 
Collecting django-reversion<2.1,>=2.0 (from aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/a5/4d/c71ad72aa87f6a25a64dc0adc707926088a8f23bfd437a70c7283a23cbf7/django_reversion-2.0.13-py2.py3-none-any.whl (85kB)
    100% |████████████████████████████████| 92kB 10.8MB/s 
Collecting django-reversion-compare~=0.8.0 (from aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/4c/cc/6225519d87e9eb3c3b400bcfd86967a5934d379a4aa395262a24e5163ac2/django_reversion_compare-0.8.4-py2.py3-none-any.whl (82kB)
    100% |████████████████████████████████| 92kB 9.7MB/s 
Collecting diff-match-patch (from aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/22/82/46eaeab04805b4fac17630b59f30c4f2c8860988bcefd730ff4f1992908b/diff-match-patch-20121119.tar.gz (54kB)
    100% |████████████████████████████████| 61kB 8.7MB/s 
Collecting django-static-precompiler (from aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/f7/52/4d0a7c1f42bbfa772e1cb8d1b015e0a35383c47bd21e79e66a551e3d6ddf/django-static-precompiler-1.8.2.tar.gz
Collecting django-autocomplete-light>=3.0.0 (from aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/ee/2c/8830276bfdb01713486585640125e0b6d0f2b4ee2ece96689a846c3d77cc/django-autocomplete-light-3.2.10.tar.gz (428kB)
    100% |████████████████████████████████| 430kB 7.3MB/s 
Collecting django-bootstrap3<9.0,>8.0 (from aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/32/6d/f40442846e38cf2cb6b51c055f087d3fe3eb54b7f27bf0983b2e73ae8f1f/django-bootstrap3-8.2.3.tar.gz
Collecting django-bootstrap3-datetimepicker-2>=2.5.0 (from aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/98/2f/de996243cc51802ff90fc9e19233e8fa68a59ddcf827482470759d0a73a0/django-bootstrap3-datetimepicker-2-2.6.0.tar.gz
Collecting django-formtools>=2.0 (from aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/97/3f/b8e04c41c028d5cdad651393abea1f686d846c717d8ab5d5ebe2974f711c/django_formtools-2.1-py2.py3-none-any.whl (132kB)
    100% |████████████████████████████████| 133kB 9.3MB/s 
Collecting django-autoslug (from aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/f2/08/1bd205d478ac2b7952bfd4eeec0a38468d068b1473fc9c17b1008e80c729/django_autoslug-1.9.3-py2.py3-none-any.whl
Collecting channels<2.0,>1.0 (from aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/7a/a6/5a3420c0b93e127fd5b22eaf4155b8c76eb7c404eeac78f4f0816fab97ce/channels-1.1.8-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 9.0MB/s 
Collecting asgi-redis (from aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/63/c0/4a2d24cbc0d163ae02bb21eaa1d95311e3948a4fd532e2d6416a02e16471/asgi_redis-1.4.3-py2.py3-none-any.whl
Collecting sqlparse (from aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/65/85/20bdd72f4537cf2c4d5d005368d502b2f464ede22982e724a82c86268eda/sqlparse-0.2.4-py2.py3-none-any.whl
Collecting dill (from aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/91/a0/19d4d31dee064fc553ae01263b5c55e7fb93daff03a69debbedee647c5a0/dill-0.2.7.1.tar.gz (64kB)
    100% |████████████████████████████████| 71kB 8.5MB/s 
Collecting django-organizations (from aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/06/7c/3ce14fd9c8de3b9c722416468fccb0c10394866252539666a63b2638b8d9/django_organizations-1.1.0-py2.py3-none-any.whl (60kB)
    100% |████████████████████████████████| 61kB 7.4MB/s 
Collecting django-improved-user==1.0a2 (from aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/7a/2c/ee4c4f605572d68116f0c08e260595d54fdda1b8de3e5fdfb4fbe8b8f2e7/django_improved_user-1.0a2-py3-none-any.whl
Collecting ply (from lesscpy->aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/a3/58/35da89ee790598a0700ea49b2a66594140f44dec458c07e8e3d4979137fc/ply-3.11-py2.py3-none-any.whl (49kB)
    100% |████████████████████████████████| 51kB 5.7MB/s 
Collecting jsonfield>=1.0.3 (from django-notifications-hq>=1.0->aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/39/ab/00f09d604f1d659831cc4d7f26419bbf2bd70852951a4f77691bd78f527e/jsonfield-2.0.2-py2.py3-none-any.whl
Collecting django-js-asset (from django-ckeditor>=5.3.0->aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/d5/96/f68c636ebedc59576c3702b2bd00cd01eb8557a4b13d50c8fbc0cf91cc47/django_js_asset-1.1.0-py2.py3-none-any.whl
Collecting daphne~=1.3 (from channels<2.0,>1.0->aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/b4/e3/65ba9a2044627826eae52f07a9013f82339bb88917aadf69c702e0e51eea/daphne-1.4.2-py2.py3-none-any.whl
Collecting asgiref~=1.1 (from channels<2.0,>1.0->aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/ee/6d/67f79a9567de5ba4419c3e8d39622bed0d974d704075d09df765b5ddb5ce/asgiref-1.1.2-py2.py3-none-any.whl
Collecting msgpack-python (from asgi-redis->aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/8a/20/6eca772d1a5830336f84aca1d8198e5a3f4715cd1c7fc36d3cc7f7185091/msgpack-python-0.5.6.tar.gz (138kB)
    100% |████████████████████████████████| 143kB 6.4MB/s 
Collecting redis~=2.10.6 (from asgi-redis->aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/3b/f6/7a76333cf0b9251ecf49efff635015171843d9b977e4ffcf59f9c4428052/redis-2.10.6-py2.py3-none-any.whl (64kB)
    100% |████████████████████████████████| 71kB 7.8MB/s 
Collecting autobahn>=0.18 (from daphne~=1.3->channels<2.0,>1.0->aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/1b/92/5753b2123802a81bda4a9cf759732dfab21baffb3bfcdac725e097df39df/autobahn-18.5.1-py2.py3-none-any.whl (294kB)
    100% |████████████████████████████████| 296kB 9.2MB/s 
Collecting twisted>=17.1 (from daphne~=1.3->channels<2.0,>1.0->aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/12/2a/e9e4fb2e6b2f7a75577e0614926819a472934b0b85f205ba5d5d2add54d0/Twisted-18.4.0.tar.bz2 (3.0MB)
    100% |████████████████████████████████| 3.0MB 5.9MB/s 
Collecting txaio>=2.10.0 (from autobahn>=0.18->daphne~=1.3->channels<2.0,>1.0->aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/dc/2e/c8a877b0a5c2798fa93ebcc1465a72a68c089e5f8b0a852ca335751dcc5a/txaio-2.10.0-py2.py3-none-any.whl
Collecting zope.interface>=4.4.2 (from twisted>=17.1->daphne~=1.3->channels<2.0,>1.0->aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/ac/8a/657532df378c2cd2a1fe6b12be3b4097521570769d4852ec02c24bd3594e/zope.interface-4.5.0.tar.gz (151kB)
    100% |████████████████████████████████| 153kB 5.7MB/s 
Collecting constantly>=15.1 (from twisted>=17.1->daphne~=1.3->channels<2.0,>1.0->aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/b9/65/48c1909d0c0aeae6c10213340ce682db01b48ea900a7d9fce7a7910ff318/constantly-15.1.0-py2.py3-none-any.whl
Collecting incremental>=16.10.1 (from twisted>=17.1->daphne~=1.3->channels<2.0,>1.0->aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/f5/1d/c98a587dc06e107115cf4a58b49de20b19222c83d75335a192052af4c4b7/incremental-17.5.0-py2.py3-none-any.whl
Collecting Automat>=0.3.0 (from twisted>=17.1->daphne~=1.3->channels<2.0,>1.0->aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/17/6a/1baf488c2015ecafda48c03ca984cf0c48c254622668eb1732dbe2eae118/Automat-0.6.0-py2.py3-none-any.whl
Collecting hyperlink>=17.1.1 (from twisted>=17.1->daphne~=1.3->channels<2.0,>1.0->aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/a7/b6/84d0c863ff81e8e7de87cff3bd8fd8f1054c227ce09af1b679a8b17a9274/hyperlink-18.0.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /home/mario/.local/lib/python3.6/site-packages (from zope.interface>=4.4.2->twisted>=17.1->daphne~=1.3->channels<2.0,>1.0->aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6)) (36.5.0)
Collecting attrs (from Automat>=0.3.0->twisted>=17.1->daphne~=1.3->channels<2.0,>1.0->aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/41/59/cedf87e91ed541be7957c501a92102f9cc6363c623a7666d69d51c78ac5b/attrs-18.1.0-py2.py3-none-any.whl
Collecting idna>=2.5 (from hyperlink>=17.1.1->twisted>=17.1->daphne~=1.3->channels<2.0,>1.0->aristotle-metadata-registry==2.0.0->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/27/cc/6dd9a3869f15c2edfab863b992838277279ce92663d334df9ecf5106f5c6/idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 14.1MB/s 
Building wheels for collected packages: django-model-utils, django-haystack-channels, pyyaml, django-haystack, django-ckeditor, diff-match-patch, django-static-precompiler, django-autocomplete-light, django-bootstrap3, django-bootstrap3-datetimepicker-2, dill, msgpack-python, twisted, zope.interface
  Running setup.py bdist_wheel for django-model-utils ... done
  Stored in directory: /home/mario/.cache/pip/wheels/ac/8a/32/32c1b37f5be2da1a7ef4a537cd3ba2b7a344d1525b235640ca
  Running setup.py bdist_wheel for django-haystack-channels ... done
  Stored in directory: /home/mario/.cache/pip/wheels/28/81/a4/df91adb31012a1a7fd230b634e2d88f1996899f8ca650f43c0
  Running setup.py bdist_wheel for pyyaml ... done
  Stored in directory: /home/mario/.cache/pip/wheels/03/05/65/bdc14f2c6e09e82ae3e0f13d021e1b6b2481437ea2f207df3f
  Running setup.py bdist_wheel for django-haystack ... done
  Stored in directory: /home/mario/.cache/pip/wheels/43/22/a0/6fcc6c32b63bb4ced16e30e5120d4758dcfc4f156073017394
  Running setup.py bdist_wheel for django-ckeditor ... done
  Stored in directory: /home/mario/.cache/pip/wheels/9b/30/86/b533836b9ff5e3cf0cfc98ffd71f7b20c1948304ae4f439bc8
  Running setup.py bdist_wheel for diff-match-patch ... done
  Stored in directory: /home/mario/.cache/pip/wheels/f2/72/a3/8c2adafbe9afc22a1e65cfc412982e0061199c0092b1be11d9
  Running setup.py bdist_wheel for django-static-precompiler ... done
  Stored in directory: /home/mario/.cache/pip/wheels/3c/6e/c2/687dc56adb3f42b6ac8613b226297d43d93422d9eb8e4607f2
  Running setup.py bdist_wheel for django-autocomplete-light ... done
  Stored in directory: /home/mario/.cache/pip/wheels/15/7a/ec/435379d140de664ba9f723dab0abb09c8c0da62ef09fc48526
  Running setup.py bdist_wheel for django-bootstrap3 ... done
  Stored in directory: /home/mario/.cache/pip/wheels/a3/af/a0/38c52d87c3a473bbcbeb5a6069433ad1857821f5b9db946245
  Running setup.py bdist_wheel for django-bootstrap3-datetimepicker-2 ... done
  Stored in directory: /home/mario/.cache/pip/wheels/1f/9b/7f/c216c213bd9cd299548b59056058d1cca153dbb25b4576c926
  Running setup.py bdist_wheel for dill ... done
  Stored in directory: /home/mario/.cache/pip/wheels/99/c4/ed/1b64d2d5809e60d5a3685530432f6159d6a9959739facb61f2
  Running setup.py bdist_wheel for msgpack-python ... done
  Stored in directory: /home/mario/.cache/pip/wheels/d5/de/86/7fa56fda12511be47ea0808f3502bc879df4e63ab168ec0406
  Running setup.py bdist_wheel for twisted ... done
  Stored in directory: /home/mario/.cache/pip/wheels/b3/76/f7/85353c829c0881e74b5366ce0ed59042b098bb4903e2da8828
  Running setup.py bdist_wheel for zope.interface ... done
  Stored in directory: /home/mario/.cache/pip/wheels/c6/b2/d2/be6785a207eaa58d76debc10c9d5c66196b40a88abb61d6af7
Successfully built django-model-utils django-haystack-channels pyyaml django-haystack django-ckeditor diff-match-patch django-static-precompiler django-autocomplete-light django-bootstrap3 django-bootstrap3-datetimepicker-2 dill msgpack-python twisted zope.interface
Installing collected packages: pytz, Django, django-model-utils, six, asgiref, txaio, autobahn, zope.interface, constantly, incremental, attrs, Automat, idna, hyperlink, twisted, daphne, channels, django-haystack, django-haystack-channels, pyyaml, ply, lesscpy, jsonfield, django-notifications-hq, django-braces, docutils, django-js-asset, django-ckeditor, pillow, django-reversion, django-reversion-compare, diff-match-patch, django-static-precompiler, django-autocomplete-light, django-bootstrap3, django-bootstrap3-datetimepicker-2, django-formtools, django-autoslug, msgpack-python, redis, asgi-redis, sqlparse, dill, django-organizations, django-improved-user, aristotle-metadata-registry
  Running setup.py develop for aristotle-metadata-registry
Successfully installed Automat-0.6.0 Django-1.11.13 aristotle-metadata-registry asgi-redis-1.4.3 asgiref-1.1.2 attrs-18.1.0 autobahn-18.5.1 channels-1.1.8 constantly-15.1.0 daphne-1.4.2 diff-match-patch-20121119 dill-0.2.7.1 django-autocomplete-light-3.2.10 django-autoslug-1.9.3 django-bootstrap3-8.2.3 django-bootstrap3-datetimepicker-2-2.6.0 django-braces-1.13.0 django-ckeditor-5.4.0 django-formtools-2.1 django-haystack-2.7.0 django-haystack-channels-0.0.1b0 django-improved-user-1.0a2 django-js-asset-1.1.0 django-model-utils-3.0.0 django-notifications-hq-1.3 django-organizations-1.1.0 django-reversion-2.0.13 django-reversion-compare-0.8.4 django-static-precompiler-1.8.2 docutils-0.14 hyperlink-18.0.0 idna-2.6 incremental-17.5.0 jsonfield-2.0.2 lesscpy-0.13.0 msgpack-python-0.5.6 pillow-5.1.0 ply-3.11 pytz-2018.4 pyyaml-3.12 redis-2.10.6 six-1.11.0 sqlparse-0.2.4 twisted-18.4.0 txaio-2.10.0 zope.interface-4.5.0
```

after it, I tried to run `python manage.py` and I got this message:

```bash
(aristotleEnv)  mario@mario-N43SM  ~/Projects/aristotle-metadata-registry/python/aristotle-metadata-registry   develop ●  python manage.py 
Traceback (most recent call last):
  File "/home/mario/miniconda3/envs/aristotleEnv/lib/python3.6/site-packages/haystack/backends/whoosh_backend.py", line 28, in <module>
    import whoosh
ModuleNotFoundError: No module named 'whoosh'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mario/miniconda3/envs/aristotleEnv/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/mario/miniconda3/envs/aristotleEnv/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/home/mario/miniconda3/envs/aristotleEnv/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mario/miniconda3/envs/aristotleEnv/lib/python3.6/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/home/mario/miniconda3/envs/aristotleEnv/lib/python3.6/site-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/home/mario/miniconda3/envs/aristotleEnv/lib/python3.6/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/mario/miniconda3/envs/aristotleEnv/lib/python3.6/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/home/mario/miniconda3/envs/aristotleEnv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mario/Projects/aristotle-metadata-registry/python/aristotle-metadata-registry/aristotle_mdr/admin.py", line 334, in <module>
    register_concept(MDR.ObjectClass)
  File "/home/mario/Projects/aristotle-metadata-registry/python/aristotle-metadata-registry/aristotle_mdr/register.py", line 51, in register_concept
    register_concept_search_index(concept_class, *args, **kwargs)
  File "/home/mario/Projects/aristotle-metadata-registry/python/aristotle-metadata-registry/aristotle_mdr/register.py", line 84, in register_concept_search_index
    connections[DEFAULT_ALIAS]._index = None
  File "/home/mario/miniconda3/envs/aristotleEnv/lib/python3.6/site-packages/haystack/utils/loading.py", line 109, in __getitem__
    self.thread_local.connections[key] = load_backend(self.connections_info[key]['ENGINE'])(using=key)
  File "/home/mario/miniconda3/envs/aristotleEnv/lib/python3.6/site-packages/haystack/utils/loading.py", line 60, in load_backend
    return import_class(full_backend_path)
  File "/home/mario/miniconda3/envs/aristotleEnv/lib/python3.6/site-packages/haystack/utils/loading.py", line 27, in import_class
    module_itself = importlib.import_module(module_path)
  File "/home/mario/miniconda3/envs/aristotleEnv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mario/Projects/aristotle-metadata-registry/python/aristotle-metadata-registry/aristotle_mdr/contrib/search_backends/facetted_whoosh.py", line 6, in <module>
    from haystack.backends import whoosh_backend as original_backend
  File "/home/mario/miniconda3/envs/aristotleEnv/lib/python3.6/site-packages/haystack/backends/whoosh_backend.py", line 30, in <module>
    raise MissingDependency("The 'whoosh' backend requires the installation of 'Whoosh'. Please refer to the documentation.")
haystack.exceptions.MissingDependency: The 'whoosh' backend requires the installation of 'Whoosh'. Please refer to the documentation.
```

After installing `whoosh`, everything went okay.
I think that inserting this package on the `install_requires` session on `setup.py` will be enough to fix it.

**Comment by LegoStormtroopr** [comment]
Were you running the tests using `tox` or just using `manage.py`?

**Comment by derrix060** [comment]
I was running direct using manage.py. I will try to use tox to see what happen.

**Comment by derrix060** [comment]
Using tox I got a bunch of different errors:

```python
GET http://127.0.0.1:9200/haystack/_mapping [status:N/A request:0.000s]
Traceback (most recent call last):
  File "/tmp/tox/dj1.11-test-linux-db-postgres-search-elastic/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/tmp/tox/dj1.11-test-linux-db-postgres-search-elastic/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/tmp/tox/dj1.11-test-linux-db-postgres-search-elastic/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/tox/dj1.11-test-linux-db-postgres-search-elastic/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 115, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/tmp/tox/dj1.11-test-linux-db-postgres-search-elastic/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/tmp/tox/dj1.11-test-linux-db-postgres-search-elastic/lib/python3.6/site-packages/urllib3/util/retry.py", line 333, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/tmp/tox/dj1.11-test-linux-db-postgres-search-elastic/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/tmp/tox/dj1.11-test-linux-db-postgres-search-elastic/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/tmp/tox/dj1.11-test-linux-db-postgres-search-elastic/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/mario/miniconda3/envs/aristotleEnv/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/mario/miniconda3/envs/aristotleEnv/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/mario/miniconda3/envs/aristotleEnv/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/mario/miniconda3/envs/aristotleEnv/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/mario/miniconda3/envs/aristotleEnv/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/tmp/tox/dj1.11-test-linux-db-postgres-search-elastic/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/tmp/tox/dj1.11-test-linux-db-postgres-search-elastic/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fec3f9fecc0>: Failed to establish a new connection: [Errno 111] Connection refused

...

Ran 733 tests in 121.126s

FAILED (errors=544)
```

And after some minutes I've aborted the job.


Anyway, I don't think that running inside or outside the tox should have any difference because tox is a tool to standardize the test environment not to trick some magic steps to make the project work, that's why I created this ticket :smile:

**Comment by harrywhite4** [comment]
So tox also installs the required dependencies in it's virtual env for you which would fix your initial error of not having whoosh installed.

The second error you are getting (when using tox) is because the tests using elasticsearch require you to be running a local elasticsearch server. If you ran the tests with the command ``tox -e dj1.11-test-linux-db-sqlite-search-whoosh`` (or with any environment that ends with search-whoosh) that should work, It will take a while to run though.

We are currently simplifying our tox config and going to have some better local testing documentation for the next release though since it isn't very clear how to run the tests during development at the moment.

**Comment by LegoStormtroopr** [comment]
I'm in the process of pulling in a new branch that will make development and basic server admin easier see #825 .

When thats in I'll have you have a look. Are you running a server from this @derrix060 ?

**Comment by derrix060** [comment]
No. I want to improve my Django skills. I remember this project from my interview and I think that helping open sources projects is a good way to learn. I want to start writing tests to this framework in a medium term.

In this meantime, I will help you guys improving the CI with more sanity checks (pep8, complexity, code smell, etc) and writing some docstrings (to learn about the existing code and help others to learn easier).

**Comment by derrix060** [comment]
It doesn't have `manage.py`, as I could see on #837  so this ticket is not valid anymore.
